### ISSUE TITLE
Remove deprecated decorators towards lit v3.0

### ISSUE THREAD

**Issue by woutermont** [digita-ai/semcom#104]
Rename `@internalProperty()` to `@state()` everywhere.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=707186612) by [Unito](https://www.unito.io)

**Comment by arnevandoorslaer** [comment]
```@internalProperty()``` is already not used in semcom

**Comment by woutermont** [comment]
Okay, perfect, I just placed this in all repos relying on XState.
