### ISSUE TITLE
Make upload component add slug header to post request

### ISSUE THREAD

**Issue by woutermont** [digita-ai/semcom#169]
The slug should be a hash of the URL of the component's code (or thus the subject of the metadata), possibly combined with the tag. @jonasbovyn will add details.

┆Issue is synchronized with this [Wrike Item](https://www.wrike.com/open.htm?id=736929665) by [Unito](https://www.unito.io)

**Comment by jonasbovyn** [comment]
Dit is de code voor het berekenen van de hash (`npm install jssha` voor het installeren van jssha)
```
const shaObj = new jsSHA('SHAKE256', 'TEXT');
shaObj.update(componentMetadata.uri);
const hash = shaObj.getHash('B64', { outputLen: 256 }).replace(/[+=/]/g, '').toLowerCase();
```
